# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from Graph import Graph
import sys
from PyQt5.QtWidgets import QApplication, QDialog, QMainWindow
import numpy as np
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore
from Graph import Graph
import random

class Ui_MainWindow(object):
    def __init__(self):
        self.graph = None
        self.centralwidget = None
        self.Mainwindow = None
        self.pushButton_close = None
        self.width = None
        self.nodes_widgets_generaL_list = []
        # label ,combobox ,connect ,Start Recording ,pgwidget, plot
        self.widget_list_node_1 = []
        self.widget_list_node_2 = []
        self.widget_list_node_3 = []
        self.widget_list_node_4 = []
        self.widget_list_node_5 = []
        self.widget_list_node_6 = []
        self.widget_list_node_7 = []
        self.widget_list_node_8 = []
        self.widget_list_node_9 = []

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

        self.Mainwindow = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, self.width - 20, self.height - 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, self.width - 40, self.height - 70))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.minimumSize = QtCore.QSize(self.width - 300, self.height - 90)
        self.setup_graph(self)
        self.verticalLayout_2.addWidget(self.pgwidget)
        #self.graphicsView = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        #self.graphicsView.setObjectName("graphicsView")
        #self.verticalLayout_2.addWidget(self.graphicsView)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_Start = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout_5.addWidget(self.pushButton_Start)
        self.comboBox_nodenumbers = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_nodenumbers.setAccessibleName("")
        self.comboBox_nodenumbers.setEditable(False)
        self.comboBox_nodenumbers.setCurrentText("")
        self.comboBox_nodenumbers.setObjectName("comboBox_nodenumbers")
        self.horizontalLayout_5.addWidget(self.comboBox_nodenumbers)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Status = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Status.setMinimumSize(QtCore.QSize(0, 100))
        self.label_Status.setObjectName("label_Status")
        self.verticalLayout.addWidget(self.label_Status)
        self.label_current_warnings = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_current_warnings.setMinimumSize(QtCore.QSize(0, 100))
        self.label_current_warnings.setObjectName("label_current_warnings")
        self.verticalLayout.addWidget(self.label_current_warnings)
        self.label_Devices_available = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Devices_available.setMinimumSize(QtCore.QSize(0, 100))
        self.label_Devices_available.setMaximumSize(QtCore.QSize(500, 300))
        self.label_Devices_available.setObjectName("label_Devices_available")
        self.verticalLayout.addWidget(self.label_Devices_available)
        self.textBrowser_statusMessages = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser_statusMessages.setMinimumSize(QtCore.QSize(0, 70))
        self.textBrowser_statusMessages.setObjectName("textBrowser_statusMessages")
        self.verticalLayout.addWidget(self.textBrowser_statusMessages)
        self.pushButton_close = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_close.setObjectName("pushButton_close")
        self.verticalLayout.addWidget(self.pushButton_close)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_1, "")



        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, self.width - 40, self.height - 70))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setGeometry(QtCore.QRect(0, 0, self.width - 40, self.height - 70))
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.widget_list_node_1.append(QtWidgets.QLabel(self.verticalLayoutWidget_3))
        self.widget_list_node_1[0].setObjectName("label_node_1")
        self.horizontalLayout_2.addWidget(self.widget_list_node_1[0])
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_signal_node_1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_signal_node_1.setObjectName("label_signal_node_1")
        self.verticalLayout_5.addWidget(self.label_signal_node_1)
        self.widget_list_node_1.append(QtWidgets.QComboBox(self.verticalLayoutWidget_3))
        self.widget_list_node_1[1].setObjectName("comboBox_node_1")
        self.verticalLayout_5.addWidget(self.widget_list_node_1[1])
        self.widget_list_node_1.append(QtWidgets.QPushButton(self.verticalLayoutWidget_3))
        self.widget_list_node_1[2].setObjectName("pushButton_change_signal_node_1")
        self.verticalLayout_5.addWidget(self.widget_list_node_1[2])
        self.widget_list_node_1.append( QtWidgets.QPushButton(self.verticalLayoutWidget_3))
        self.widget_list_node_1[3].setObjectName("pushButton_Record_node_1")
        self.verticalLayout_5.addWidget(self.widget_list_node_1[3])
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.widget_list_node_1.append(pg.GraphicsLayoutWidget(show=True))
        self.widget_list_node_1.append(self.widget_list_node_1[4].addPlot())
        #self.graphicsView_node_1 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_3)
        #self.graphicsView_node_1.setObjectName("graphicsView_node_1")
        self.horizontalLayout_2.addWidget(self.widget_list_node_1[4])
        #self.horizontalLayout_2.addWidget(self.graphicsView_node_1)
        self.nodes_widgets_generaL_list.append(self.widget_list_node_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.widget_list_node_2.append(QtWidgets.QLabel(self.verticalLayoutWidget_3))
        self.widget_list_node_2[0].setObjectName("label_node_2")
        self.horizontalLayout_4.addWidget(self.widget_list_node_2[0])
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_signal_node_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_signal_node_2.setObjectName("label_signal_node_2")
        self.verticalLayout_7.addWidget(self.label_signal_node_2)
        self.widget_list_node_2.append(QtWidgets.QComboBox(self.verticalLayoutWidget_3))
        self.widget_list_node_2[1].setObjectName("comboBox_node_2")
        self.verticalLayout_7.addWidget(self.widget_list_node_2[1])
        self.widget_list_node_2.append(QtWidgets.QPushButton(self.verticalLayoutWidget_3))
        self.widget_list_node_2[2].setObjectName("pushButton_change_signal_node_2")
        self.verticalLayout_7.addWidget(self.widget_list_node_2[2])
        self.widget_list_node_2.append(QtWidgets.QPushButton(self.verticalLayoutWidget_3))
        self.widget_list_node_2[3].setObjectName("pushButton_Record_node_2")
        self.verticalLayout_7.addWidget(self.widget_list_node_2[3])
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.widget_list_node_2.append(pg.GraphicsLayoutWidget(show=True))
        self.widget_list_node_2.append(self.widget_list_node_2[4].addPlot())
        #self.graphicsView_node_2 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_3)
        #self.graphicsView_node_2.setObjectName("graphicsView_node_2")
        self.horizontalLayout_4.addWidget(self.widget_list_node_2[4])
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.nodes_widgets_generaL_list.append(self.widget_list_node_2)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_list_node_3.append(QtWidgets.QLabel(self.verticalLayoutWidget_3))
        self.widget_list_node_3[0].setObjectName("label_node_3")
        self.horizontalLayout_3.addWidget(self.widget_list_node_3[0])
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_signal_node_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_signal_node_3.setObjectName("label_signal_node_3")
        self.verticalLayout_6.addWidget(self.label_signal_node_3)
        self.widget_list_node_3.append(QtWidgets.QComboBox(self.verticalLayoutWidget_3))
        self.widget_list_node_3[1].setObjectName("comboBox_node_3")
        self.verticalLayout_6.addWidget(self.widget_list_node_3[1])
        self.widget_list_node_3.append(QtWidgets.QPushButton(self.verticalLayoutWidget_3))
        self.widget_list_node_3[2].setObjectName("pushButton_change_signal_node_3")
        self.verticalLayout_6.addWidget(self.widget_list_node_3[2])
        self.widget_list_node_3.append(QtWidgets.QPushButton(self.verticalLayoutWidget_3))
        self.widget_list_node_3[3].setObjectName("pushButton_Record_node_3")
        self.verticalLayout_6.addWidget(self.widget_list_node_3[3])
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.widget_list_node_3.append(pg.GraphicsLayoutWidget(show=True))
        self.widget_list_node_3.append(self.widget_list_node_3[4].addPlot())
        #self.graphicsView_node_4 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_3)
        #self.graphicsView_node_4.setObjectName("graphicsView_node_4")
        self.horizontalLayout_3.addWidget(self.widget_list_node_3[4])
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.nodes_widgets_generaL_list.append(self.widget_list_node_3)
        self.tabWidget.addTab(self.tab_2, "")


        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, self.width - 40, self.height - 70))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setGeometry(QtCore.QRect(0, 0, self.width - 40, self.height - 70))
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_list_node_4.append(QtWidgets.QLabel(self.verticalLayoutWidget_4))
        self.widget_list_node_4[0].setObjectName("label_node_4")
        self.horizontalLayout_6.addWidget(self.widget_list_node_4[0])
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_signal_node_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_signal_node_4.setObjectName("label_signal_node_4")
        self.verticalLayout_8.addWidget(self.label_signal_node_4)
        self.widget_list_node_4.append(QtWidgets.QComboBox(self.verticalLayoutWidget_4))
        self.widget_list_node_4[1].setObjectName("comboBox_node_4")
        self.verticalLayout_8.addWidget(self.widget_list_node_4[1])
        self.widget_list_node_4.append(QtWidgets.QPushButton(self.verticalLayoutWidget_4))
        self.widget_list_node_4[2].setObjectName("pushButton_8")
        self.verticalLayout_8.addWidget(self.widget_list_node_4[2])
        self.widget_list_node_4.append(QtWidgets.QPushButton(self.verticalLayoutWidget_4))
        self.widget_list_node_4[3].setObjectName("pushButton_Record_node_6")
        self.verticalLayout_8.addWidget(self.widget_list_node_4[3])
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.widget_list_node_4.append(pg.GraphicsLayoutWidget(show=True))
        self.widget_list_node_4.append(self.widget_list_node_4[4].addPlot())
        self.horizontalLayout_6.addWidget(self.widget_list_node_4[4])
        self.nodes_widgets_generaL_list.append(self.widget_list_node_4)

        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_list_node_5.append(QtWidgets.QLabel(self.verticalLayoutWidget_4))
        self.widget_list_node_5[0].setObjectName("label_node_5")
        self.horizontalLayout_7.addWidget(self.widget_list_node_5[0])
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_signal_node_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_signal_node_5.setObjectName("label_signal_node_5")
        self.verticalLayout_9.addWidget(self.label_signal_node_5)
        self.widget_list_node_5.append(QtWidgets.QComboBox(self.verticalLayoutWidget_4))
        self.widget_list_node_5[1].setObjectName("comboBox_node_5")
        self.verticalLayout_9.addWidget(self.widget_list_node_5[1])
        self.widget_list_node_5.append(QtWidgets.QPushButton(self.verticalLayoutWidget_4))
        self.widget_list_node_5[2].setObjectName("pushButton_10")
        self.verticalLayout_9.addWidget(self.widget_list_node_5[2])
        self.widget_list_node_5.append(QtWidgets.QPushButton(self.verticalLayoutWidget_4))
        self.widget_list_node_5[3].setObjectName("pushButton_Record_node_7")
        self.verticalLayout_9.addWidget(self.widget_list_node_5[3])
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.widget_list_node_5.append(pg.GraphicsLayoutWidget(show=True))
        self.widget_list_node_5.append(self.widget_list_node_5[4].addPlot())
        self.horizontalLayout_7.addWidget(self.widget_list_node_5[4])
        self.nodes_widgets_generaL_list.append(self.widget_list_node_5)

        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_list_node_6.append(QtWidgets.QLabel(self.verticalLayoutWidget_4))
        self.widget_list_node_6[0].setObjectName("label_node_6")
        self.horizontalLayout_8.addWidget(self.widget_list_node_6[0])
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_signal_node_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_signal_node_6.setObjectName("label_signal_node_6")
        self.verticalLayout_10.addWidget(self.label_signal_node_6)
        self.widget_list_node_6.append(QtWidgets.QComboBox(self.verticalLayoutWidget_4))
        self.widget_list_node_6[1].setObjectName("comboBox_node_6")
        self.verticalLayout_10.addWidget(self.widget_list_node_6[1])
        self.widget_list_node_6.append(QtWidgets.QPushButton(self.verticalLayoutWidget_4))
        self.widget_list_node_6[2].setObjectName("pushButton_12")
        self.verticalLayout_10.addWidget(self.widget_list_node_6[2])
        self.widget_list_node_6.append(QtWidgets.QPushButton(self.verticalLayoutWidget_4))
        self.widget_list_node_6[3].setObjectName("pushButton_Record_node_8")
        self.verticalLayout_10.addWidget(self.widget_list_node_6[3])
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.widget_list_node_6.append(pg.GraphicsLayoutWidget(show=True))
        self.widget_list_node_6.append(self.widget_list_node_6[4].addPlot())
        self.horizontalLayout_8.addWidget(self.widget_list_node_6[4])
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.nodes_widgets_generaL_list.append(self.widget_list_node_6)
        self.tabWidget.addTab(self.tab_3, "")



        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(0, 0, self.width - 40, self.height - 70))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setGeometry(QtCore.QRect(0, 0, self.width - 40, self.height - 70))
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")

        self.widget_list_node_7.append(QtWidgets.QLabel(self.verticalLayoutWidget_9))
        self.widget_list_node_7[0].setObjectName("label_node_7")
        self.horizontalLayout_9.addWidget(self.widget_list_node_7[0])
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.widget_list_node_7.append(QtWidgets.QComboBox(self.verticalLayoutWidget_9))
        self.widget_list_node_7[1].setObjectName("comboBox_node_7")
        self.verticalLayout_12.addWidget(self.widget_list_node_7[1])
        self.widget_list_node_7.append(QtWidgets.QPushButton(self.verticalLayoutWidget_9))
        self.widget_list_node_7[2].setObjectName("pushButton_14")
        self.verticalLayout_12.addWidget(self.widget_list_node_7[2])
        self.widget_list_node_7.append(QtWidgets.QPushButton(self.verticalLayoutWidget_9))
        self.widget_list_node_7[3].setObjectName("pushButton_15")
        self.verticalLayout_12.addWidget(self.widget_list_node_7[3])
        self.horizontalLayout_9.addLayout(self.verticalLayout_12)
        self.widget_list_node_7.append(pg.GraphicsLayoutWidget(show=True))
        self.widget_list_node_7.append(self.widget_list_node_7[4].addPlot())
        self.horizontalLayout_9.addWidget(self.widget_list_node_7[4])
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.nodes_widgets_generaL_list.append(self.widget_list_node_7)

        self.widget_list_node_8.append(QtWidgets.QLabel(self.verticalLayoutWidget_9))
        self.widget_list_node_8[0].setObjectName("label_node_8")
        self.horizontalLayout_10.addWidget(self.widget_list_node_8[0])
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_13.addWidget(self.label_16)
        self.widget_list_node_8.append(QtWidgets.QComboBox(self.verticalLayoutWidget_9))
        self.widget_list_node_8[1].setObjectName("comboBox_node_8")
        self.verticalLayout_13.addWidget(self.widget_list_node_8[1])
        self.widget_list_node_8.append(QtWidgets.QPushButton(self.verticalLayoutWidget_9))
        self.widget_list_node_8[2].setObjectName("pushButton_16")
        self.verticalLayout_13.addWidget(self.widget_list_node_8[2])
        self.widget_list_node_8.append(QtWidgets.QPushButton(self.verticalLayoutWidget_9))
        self.widget_list_node_8[3].setObjectName("pushButton_17")
        self.verticalLayout_13.addWidget(self.widget_list_node_8[3])
        self.horizontalLayout_10.addLayout(self.verticalLayout_13)
        self.widget_list_node_8.append(pg.GraphicsLayoutWidget(show=True))
        self.widget_list_node_8.append(self.widget_list_node_8[4].addPlot())
        self.horizontalLayout_10.addWidget(self.widget_list_node_8[4])
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.nodes_widgets_generaL_list.append(self.widget_list_node_8)


        self.widget_list_node_9.append(QtWidgets.QLabel(self.verticalLayoutWidget_9))
        self.widget_list_node_9[0].setObjectName("label_node_9")
        self.horizontalLayout_11.addWidget(self.widget_list_node_9[0])
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_14.addWidget(self.label_18)
        self.widget_list_node_9.append(QtWidgets.QComboBox(self.verticalLayoutWidget_9))
        self.widget_list_node_9[1].setObjectName("comboBox_node_9")
        self.verticalLayout_14.addWidget(self.widget_list_node_9[1])
        self.widget_list_node_9.append(QtWidgets.QPushButton(self.verticalLayoutWidget_9))
        self.widget_list_node_9[2].setObjectName("pushButton_18")
        self.verticalLayout_14.addWidget(self.widget_list_node_9[2])
        self.widget_list_node_9.append( QtWidgets.QPushButton(self.verticalLayoutWidget_9))
        self.widget_list_node_9[3].setObjectName("pushButton_19")
        self.verticalLayout_14.addWidget(self.widget_list_node_9[3])
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        self.widget_list_node_9.append(pg.GraphicsLayoutWidget(show=True))
        self.widget_list_node_9.append(self.widget_list_node_9[4].addPlot())
        self.horizontalLayout_11.addWidget(self.widget_list_node_9[4])
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tab_4, "")
        self.nodes_widgets_generaL_list.append(self.widget_list_node_9)



        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.comboBox_nodenumbers.setPlaceholderText(_translate("MainWindow", "select_number_of_nodes"))
        self.label_Status.setText(_translate("MainWindow", "Status Clear !!"))
        self.label_current_warnings.setText(_translate("MainWindow", "No warnings"))
        self.pushButton_close.setText(_translate("MainWindow", "Close"))
        self.label_Devices_available.setText(_translate("MainWindow", "Devices: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Sensor Network"))
        for i in range(0,len(self.nodes_widgets_generaL_list)):
            for a in range(0,4):
                if a == 0:
                    self.nodes_widgets_generaL_list[i][a].setText(_translate("MainWindow", "Node {}  ".format(i)))
                elif a == 1:
                    pass
                elif a == 2:
                    self.nodes_widgets_generaL_list[i][a].setText(_translate("MainWindow", "Connect"))
                else:
                    self.nodes_widgets_generaL_list[i][a].setText(_translate("MainWindow", "Start Recording"))



        self.label_signal_node_1.setText(_translate("MainWindow", "Signal"))

        self.label_signal_node_2.setText(_translate("MainWindow", "Signal"))

        self.label_signal_node_3.setText(_translate("MainWindow", "Signal"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Maschine Overview Page 1"))
        self.label_signal_node_4.setText(_translate("MainWindow", "Signal"))
        self.label_signal_node_5.setText(_translate("MainWindow", "Signal"))
        self.label_signal_node_6.setText(_translate("MainWindow", "Signal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Maschine Overview Page 2"))

        self.label_14.setText(_translate("MainWindow", "Signal"))

        self.label_16.setText(_translate("MainWindow", "Signal"))

        self.label_18.setText(_translate("MainWindow", "Signal"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Maschine Overview Page 3"))

    def define_width_and_height(self, width, height):
        self.width = width
        self.height = height

    def close_window(self):
        self.Mainwindow.close()

    def setup_nodes(self, numberofnodes):
        node_definitions = []
        print(node_definitions)
        for i in range(0, numberofnodes):
            if (i % 2) == 0:
                node_definitions.append((0 + 10 * i, i))
            else:
                if (i % 3) == 0:
                    node_definitions.append((i * 10, 0 + 10 * i))
                else:
                    node_definitions.append((i, 0 + 10 * i))
        return np.array(node_definitions, dtype=float)


    def init_random_nodecon(self, numberofnodes):
        node_connections = []
        for i in range(0, numberofnodes):
            a = random.randrange(0, numberofnodes)
            b = random.randrange(0, numberofnodes)
            node_connections.append((a, b))
        return np.array(node_connections)

    def setup_graph(self, Mainwindow):
        # self.verticalLayout_2.addWidget(self.pgwidget)
        self.graph = Graph()
        # self.horizontalLayout.addItem(self.graph)
        # self.graphicsView = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        # self.graphicsView.setObjectName("graphicsView")
        self.pgwidget = pg.GraphicsLayoutWidget(show=True)

        bs = self.pgwidget.addViewBox()
        bs.addItem(self.graph)
        pg.setConfigOptions(antialias=True)
        #self.nodespos = self.setup_nodes(6)
        ## Define positions of nodes

        ## Define the set of connections in the graph
        #self.nodesadj = self.init_random_nodecon(6)

        ## Define the symbol to use for each node (this is optional)
        #self.nodessymbols = ['o', 'o', 'o', 'o', 't', '+']

        ## Define the line style for each connection (this is optional)
        # self.nodeslines = np.array([
        #     (255, 0, 0, 255, 1),
        #     (255, 0, 255, 255, 2),
        #     (255, 0, 255, 255, 3),
        #     (255, 255, 0, 255, 2),
        #     (255, 0, 0, 255, 1),
        #     (255, 255, 255, 255, 4),
        # ], dtype=[('red', np.ubyte), ('green', np.ubyte), ('blue', np.ubyte), ('alpha', np.ubyte), ('width', float)])

        ## Define text to show next to each symbol
        #texts = ["Point %d" % i for i in range(6)]
        #self.graph.setData(pos=self.nodespos, adj=self.nodesadj, size=1, symbol=self.nodessymbols,pxMode=False, text=texts)


